/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: b707ecd5ae46ce87d3d42ea6aeb6bd02)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface CiEnv {
		AWS_REGION: "us-west-2";
		ENVIRONMENT: "ci";
		VERSION: "@@VERSION@@-ci";
		RETURN_STACK_TRACES: "false";
		DA_ORIGIN: "https://admin.da.live";
		LANGFUSE_PUBLIC_KEY: "";
		LANGFUSE_SECRET_KEY: "";
		LANGFUSE_BASEURL: "";
		AWS_BEARER_TOKEN_BEDROCK: string;
		DAADMIN: Fetcher /* da-admin-stage */;
		DACOLLAB: Fetcher /* da-collab-stage */;
	}
	interface ProductionEnv {
		AWS_REGION: "us-west-2";
		ENVIRONMENT: "production";
		VERSION: "@@VERSION@@";
		RETURN_STACK_TRACES: "false";
		DA_ORIGIN: "https://admin.da.live";
		LANGFUSE_PUBLIC_KEY: "";
		LANGFUSE_SECRET_KEY: "";
		LANGFUSE_BASEURL: "";
		AWS_BEARER_TOKEN_BEDROCK: string;
		DAADMIN: Fetcher /* da-admin */;
		DACOLLAB: Fetcher /* da-collab */;
	}
	interface DevEnv {
		AWS_REGION: "us-west-2";
		ENVIRONMENT: "dev";
		VERSION: "0.0.0-dev";
		RETURN_STACK_TRACES: "true";
		DA_ORIGIN: "http://localhost:8787";
		LANGFUSE_PUBLIC_KEY: "";
		LANGFUSE_SECRET_KEY: "";
		LANGFUSE_BASEURL: "";
		AWS_BEARER_TOKEN_BEDROCK: string;
		DAADMIN: Fetcher /* da-admin-local */;
		DACOLLAB: Fetcher /* da-collab-local */;
	}
	interface Env {
		AWS_BEARER_TOKEN_BEDROCK: string;
		AWS_REGION?: "us-west-2";
		ENVIRONMENT?: "ci" | "production" | "dev";
		VERSION?: "@@VERSION@@-ci" | "@@VERSION@@" | "0.0.0-dev";
		RETURN_STACK_TRACES?: "false" | "true";
		DA_ORIGIN?: "https://admin.da.live" | "http://localhost:8787";
		LANGFUSE_PUBLIC_KEY?: "";
		LANGFUSE_SECRET_KEY?: "";
		LANGFUSE_BASEURL?: "";
		DAADMIN?: Fetcher /* da-admin-stage */ | Fetcher /* da-admin */ | Fetcher /* da-admin-local */;
		DACOLLAB?: Fetcher /* da-collab-stage */ | Fetcher /* da-collab */ | Fetcher /* da-collab-local */;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AWS_REGION" | "ENVIRONMENT" | "VERSION" | "RETURN_STACK_TRACES" | "DA_ORIGIN" | "LANGFUSE_PUBLIC_KEY" | "LANGFUSE_SECRET_KEY" | "LANGFUSE_BASEURL" | "AWS_BEARER_TOKEN_BEDROCK">> {}
}
