/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 64d48df1142f6c16245ed443f0f2caff)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/server');
  }
  interface CiEnv {
    AWS_REGION: 'us-west-2';
    ENVIRONMENT: 'ci';
    VERSION: '@@VERSION@@-ci';
    RETURN_STACK_TRACES: 'false';
    DA_ORIGIN: 'https://admin.da.live';
    LANGFUSE_BASEURL: 'https://mystique-langfuse-prod.corp.ethos117-prod-va6.ethos.adobe.net/';
    AWS_BEARER_TOKEN_BEDROCK: string;
    LANGFUSE_PUBLIC_KEY: string;
    LANGFUSE_SECRET_KEY: string;
    DAADMIN: Fetcher /* da-admin-stage */;
    DACOLLAB: Fetcher /* da-collab-stage */;
  }
  interface ProductionEnv {
    AWS_REGION: 'us-west-2';
    ENVIRONMENT: 'production';
    VERSION: '@@VERSION@@';
    RETURN_STACK_TRACES: 'false';
    DA_ORIGIN: 'https://admin.da.live';
    LANGFUSE_BASEURL: 'https://mystique-langfuse-prod.corp.ethos117-prod-va6.ethos.adobe.net/';
    AWS_BEARER_TOKEN_BEDROCK: string;
    LANGFUSE_PUBLIC_KEY: string;
    LANGFUSE_SECRET_KEY: string;
    DAADMIN: Fetcher /* da-admin */;
    DACOLLAB: Fetcher /* da-collab */;
  }
  interface DevEnv {
    AWS_REGION: 'us-west-2';
    ENVIRONMENT: 'dev';
    VERSION: '0.0.0-dev';
    RETURN_STACK_TRACES: 'true';
    DA_ORIGIN: 'http://localhost:8787';
    LANGFUSE_BASEURL: 'https://mystique-langfuse-prod.corp.ethos117-prod-va6.ethos.adobe.net/';
    AWS_BEARER_TOKEN_BEDROCK: string;
    LANGFUSE_PUBLIC_KEY: string;
    LANGFUSE_SECRET_KEY: string;
    DAADMIN: Fetcher /* da-admin-local */;
    DACOLLAB: Fetcher /* da-collab-local */;
  }
  interface Env {
    AWS_BEARER_TOKEN_BEDROCK: string;
    LANGFUSE_PUBLIC_KEY: string;
    LANGFUSE_SECRET_KEY: string;
    AWS_REGION?: 'us-west-2';
    ENVIRONMENT?: 'ci' | 'production' | 'dev';
    VERSION?: '@@VERSION@@-ci' | '@@VERSION@@' | '0.0.0-dev';
    RETURN_STACK_TRACES?: 'false' | 'true';
    DA_ORIGIN?: 'https://admin.da.live' | 'http://localhost:8787';
    LANGFUSE_BASEURL?: 'https://mystique-langfuse-prod.corp.ethos117-prod-va6.ethos.adobe.net/';
    DAADMIN?: Fetcher /* da-admin-stage */ | Fetcher /* da-admin */ | Fetcher /* da-admin-local */;
    DACOLLAB?:
      | Fetcher /* da-collab-stage */
      | Fetcher /* da-collab */
      | Fetcher /* da-collab-local */;
    /** Feature flag: set to "true" to enable generated tools loading */
    GENERATED_TOOLS_ENABLED?: string;
    /** URL of the da-generated-tools-sandbox Worker (Phase 1+) */
    GENERATED_TOOLS_SANDBOX_URL?: string;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'AWS_REGION'
      | 'ENVIRONMENT'
      | 'VERSION'
      | 'RETURN_STACK_TRACES'
      | 'DA_ORIGIN'
      | 'LANGFUSE_BASEURL'
      | 'AWS_BEARER_TOKEN_BEDROCK'
      | 'LANGFUSE_PUBLIC_KEY'
      | 'LANGFUSE_SECRET_KEY'
    >
  > {}
}
