/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: c6bfaaa6115db8b6e5ecce1d10b3289a)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env {
		AWS_REGION: string;
		AWS_BEARER_TOKEN_BEDROCK: string;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
		DAADMIN: Fetcher /* da-admin */;
		DACOLLAB: Fetcher /* da-collab */;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AWS_REGION" | "AWS_BEARER_TOKEN_BEDROCK">> {}
}
