# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "da-agent"
main = "src/server.ts"
compatibility_date = "2026-01-28"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[observability]
enabled = true

[dev]
port = 5173

# ----------------------------------------------------------------------
# CI environment
[env.ci]
name = "da-agent-ci"

services = [
  { binding = "DAADMIN", service = "da-admin-stage" },
  { binding = "DACOLLAB", service = "da-collab-stage" },
]

[env.ci.vars]
AWS_REGION = "us-west-2"
ENVIRONMENT = "ci"
VERSION = "@@VERSION@@-ci"
RETURN_STACK_TRACES = "false"
DA_ORIGIN = "https://admin.da.live"
LANGFUSE_PUBLIC_KEY = ""
LANGFUSE_SECRET_KEY = ""
LANGFUSE_BASEURL = ""

# ----------------------------------------------------------------------
# production environment
[env.production]
name = "da-agent"

services = [
  { binding = "DAADMIN", service = "da-admin" },
  { binding = "DACOLLAB", service = "da-collab" },
]

[env.production.vars]
AWS_REGION = "us-west-2"
ENVIRONMENT = "production"
VERSION = "@@VERSION@@"
RETURN_STACK_TRACES = "false"
DA_ORIGIN = "https://admin.da.live"
LANGFUSE_PUBLIC_KEY = ""
LANGFUSE_SECRET_KEY = ""
LANGFUSE_BASEURL = ""

# ----------------------------------------------------------------------
# dev environment (local)
[env.dev]
name = "da-agent-local"

services = [
  { binding = "DAADMIN", service = "da-admin-local" },
  { binding = "DACOLLAB", service = "da-collab-local" },
]

[env.dev.vars]
AWS_REGION = "us-west-2"
ENVIRONMENT = "dev"
VERSION="0.0.0-dev"
RETURN_STACK_TRACES = "true"
DA_ORIGIN = "http://localhost:8787"
LANGFUSE_PUBLIC_KEY = ""
LANGFUSE_SECRET_KEY = ""
LANGFUSE_BASEURL = ""
