# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "da-agent"
main = "src/server.ts"
compatibility_date = "2026-01-28"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[observability]
enabled = true

[dev]
port = 4200

# ----------------------------------------------------------------------
# CI environment
[env.ci]
name = "da-agent-ci"

services = [
  { binding = "DAADMIN", service = "da-admin-stage" },
  { binding = "DACOLLAB", service = "da-collab-stage" },
  { binding = "AEM_AGENTIC_PLUGINS", service = "aem-agentic-plugins-ci" },
]

[env.ci.vars]
AWS_REGION = "us-west-2"
ENVIRONMENT = "ci"
VERSION = "@@VERSION@@-ci"
RETURN_STACK_TRACES = "false"
DA_ORIGIN = "https://admin.da.live"
LANGFUSE_BASEURL = "https://mystique-langfuse-prod.ethos117-prod-va6.ethos.adobe.net/"
GOVERNANCE_AGENT_URL = "https://enterprise-context.adobe.io/mcp/"
DA_SC_MCP_URL = "https://da-sc-mcp-ci.adobeaem.workers.dev/mcp/"
TRUSTED_MCP_DOMAINS = "*.adobe.io,*.adobe.net,*.adobe.com, *.adobeaem.workers.dev, mcp.adobeaemcloud.com, d31bkz463thsuv.cloudfront.net, mcp.aem.services, *.mcp.aem.services"

# ----------------------------------------------------------------------
# production environment
[env.production]
name = "da-agent"

services = [
  { binding = "DAADMIN", service = "da-admin" },
  { binding = "DACOLLAB", service = "da-collab" },
  { binding = "AEM_AGENTIC_PLUGINS", service = "aem-agentic-plugins" },
]

[env.production.vars]
AWS_REGION = "us-west-2"
ENVIRONMENT = "production"
VERSION = "@@VERSION@@"
RETURN_STACK_TRACES = "false"
DA_ORIGIN = "https://admin.da.live"
LANGFUSE_BASEURL = "https://mystique-langfuse-prod.ethos117-prod-va6.ethos.adobe.net/"
GOVERNANCE_AGENT_URL = "https://enterprise-context.adobe.io/mcp/"
DA_SC_MCP_URL = "https://da-sc-mcp.adobeaem.workers.dev/mcp/"
TRUSTED_MCP_DOMAINS = "*.adobe.io,*.adobe.net,*.adobe.com, *.adobeaem.workers.dev, mcp.adobeaemcloud.com, d31bkz463thsuv.cloudfront.net"

# ----------------------------------------------------------------------
# dev environment (local)
[env.dev]
name = "da-agent-local"

services = [
  { binding = "DAADMIN", service = "da-admin-local" },
  { binding = "DACOLLAB", service = "da-collab-local" },
]

[env.dev.vars]
AWS_REGION = "us-west-2"
ENVIRONMENT = "dev"
VERSION="0.0.0-dev"
RETURN_STACK_TRACES = "true"
DA_ORIGIN = "http://localhost:8787"
LANGFUSE_BASEURL = "https://mystique-langfuse-prod.ethos117-prod-va6.ethos.adobe.net/"
GOVERNANCE_AGENT_URL = "https://enterprise-context-stage.adobe.io/mcp/"
DA_SC_MCP_URL = "https://da-sc-mcp-ci.adobeaem.workers.dev/mcp/"
TRUSTED_MCP_DOMAINS = "*.adobe.io,*.adobe.net,*.adobe.com, *.adobeaem.workers.dev, mcp.adobeaemcloud.com, d31bkz463thsuv.cloudfront.net"
